# Copy to root
# Martin Bykov 2024-2025

name: Kopírování (main)

on:
  push:
     branches: [main]
    
jobs:
   codecount:
    runs-on: ubuntu-latest
    name: Copying
    steps:
      - name: Načtení repozitáře
        uses: actions/checkout@v4
      - name: Spušťení skriptu 
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
          bash "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
      - name: Uložení změn
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github chalupní kopírka (akce)"
          git add -A
          if [[ -n $(git commit -am "Překopírování souborů do složky root") ]]; then
            echo "1=1" >> "$GITHUB_OUTPUT"
          else
            echo "0=1" >> "$GITHUB_OUTPUT"
          fi
          git push
      
