# Copy to root and run python script
# Martin Bykov 2024-2025

name: Skripty a procesování

on:
  push:
     branches: [main]
    
jobs:
   codecount:
    runs-on: ubuntu-latest
    name: Kopírování (main)
    steps:
      - name: Načtení repozitáře
        uses: actions/checkout@v4
      - name: Spušťení skriptu 
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
          bash "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
      - name: Uložení změn
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github chalupní kopírka (akce)"
          git add -A
          if [[ -n $(git commit -am "Překopírování souborů do složky root") ]]; then
            echo "1=1"
            echo "1=1" >> "$GITHUB_OUTPUT"
          else
            echo "0=1"
            echo "0=1" >> "$GITHUB_OUTPUT"
          fi
          git push
    mkdocs:
      runs-on: ubuntu-latest
      name: Generátor dokumentace
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs pytest pytest-timeout httpx
      # download files from all repos prefixed saved in repos list
      - name: Downloading
        run: |
          python .github/workflows/mkdocs.py
          
      
