# Copy to root and run python script
# Martin Bykov 2024-2025

name: Skripty a procesování

on:
  push:
    branches: [main]
    
jobs:
  codecount:
    runs-on: ubuntu-latest
    name: Kopírování (main)
    steps:
      - name: Načtení repozitáře
        uses: actions/checkout@v4
      - name: Spušťení skriptu 
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
          bash "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
      - name: Uložení změn
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github chalupní kopírka (akce)"
          git add -A
          if [[ -n $(git commit -am "Překopírování souborů do složky root") ]]; then
            echo "1=1"
            echo "1=1" >> "$GITHUB_OUTPUT"
          else
            echo "0=1"
            echo "0=1" >> "$GITHUB_OUTPUT"
          fi
          git push
    
  mkdocs:
    runs-on: ubuntu-latest
    name: Generátor dokumentace
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-timeout httpx mkdocs mkdocs-bootswatch mkdocs-exclude
      # download files from all repos prefixed saved in repos list
      - name: Generating
        run: |
          git pull
          mkdir temp
          python .github/workflows/mkdocs/mkdocsgen.py
          cd temp
          mkdocs gh-deploy --config-file ../mkdocs.yml
      - name: Kopírování assetů (docresource)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github chalupní kopírka (akce)"

          git fetch
          git checkout gh-pages
                    
          git restore --source main temp/docresource

      - name: Cleanup on main
        run: |
          git checkout main
          rm -r temp
          
          
      
